version = "0.1.0"

[[recipe]]
name = "build"
alias = "b"
description = "Build release binary"
arguments = []
command = "cargo build --release"

[[recipe]]
name = "run"
alias = "r"
description = "Compile and run"
arguments = ["*rest"]
command = ["cargo", "run", "--", ["*rest"]]

[[recipe]]
name = "test"
alias = "t"
description = "Run tests"
arguments = ["*rest"]
command = ["cargo", "test", ["*rest"]]

[[recipe]]
name = "version"
alias = "v"
description = "Set or get version"
arguments = ["?version"]
command = ["./scripts/version.sh", ["?version"]]
