version = "0.1.0"

[[recipe]]
names = ["build", "b"]
description = "Build release binary"
arguments = []
command = "cargo build --release"

[[recipe]]
names = ["run", "r"]
description = "Compile and run"
arguments = ["*rest"]
command = ["cargo", "run", "--", ["*rest"]]

[[recipe]]
names = ["test", "t"]
description = "Run tests"
arguments = ["*rest"]
command = ["cargo", "test", ["*rest"]]

[[recipe]]
names = ["version", "v"]
description = "Set or get version"
arguments = ["?version"]
command = ["./scripts/version.sh", ["?version"]]
