[[recipes]]
names = ["build", "b"]
description = "Build release binary"
arguments = []
command = ["cargo", "build", "--release"]

[[recipes]]
names = ["run", "r"]
description = "Compile and run"
arguments = ["*rest"]
command = ["cargo", "run", "--", ["*rest"]]

[[recipes]]
names = ["test", "t"]
description = "Run tests"
arguments = ["*rest"]
command = ["cargo", "test", ["*rest"]]

[[recipes]]
names = ["version", "v"]
description = "Set or get version"
arguments = ["?version"]
command = ["./scripts/version.sh", ["?version"]]

[[recipes]]
names = ["dummy"]
description = "Dummy recipe that prints arguments"
arguments = ["first", "*rest"]
command = ["./scripts/dummy.sh", ["first"], ["*rest"]]
